<?php

namespace App\Controllers;
use Core\Controller;

class UserController extends Controller
{
    public function index()
    {

    }

    public function show()
    {

    }

    public function before(string $action, array $params = []): bool
    {
        if ($action === 'show' && $params['user'] !== 'admin') {
            return false;
        }

        return parent::before($action, $params); // TODO: Change the autogenerated stub
    }
}